### ISSUE TITLE
Should we work together?

### ISSUE THREAD

**Issue by bizz84** [martin-bertele/ftcon24eu#1]
Thanks for this repo!

Seems like we had the same idea as I also published something similar at the same time:

https://github.com/bizz84/ftcon24eu_talks

Since you made more progress on yours, I'd be happy to use and contribute to yours.

How would you like to move forward?

**Comment by martin-bertele** [comment]
Thank you for yours! 
I've played with different sorts of ordering / displaying the same data which gets automatically updated upon edits to the json files.

I believe since you are closer connected to speakers, whats your proposal?

I'm also happy to use and contribute to yours. I'm pretty sure ChatGPT could easily prefill all talk titles and speaker names to your README by feeding mine.

I've created it to also from time to time when I (or others) dig into talks and find some "recommendations" to add it to the jsons. VideoUrl, level and topics are still missing - those I was going to finalize when the links are out.

**Comment by martin-bertele** [comment]
@bizz84 if you ask speakers to fill data into my prepared jsons, I'm happy to generate the README for yours (could even be automated).
Those who already filled yours, I can easily copy over into mine.

what do you think?

**Comment by bizz84** [comment]
@martin-bertele sounds good. I'll send out a tweet today. 👍

**Comment by martin-bertele** [comment]
> @martin-bertele sounds good. I'll send out a tweet today. 👍

awesome, I have copied the current status from yours over

**Comment by bizz84** [comment]
Great, thanks! I've added a note with a redirect to my README and made another post on LinkedIn/Twitter. Hopefully more people will submit a PR to this repo. 🙂

**Comment by martin-bertele** [comment]
I have added an acknowledgement to the introduction and apology @bizz84 for this coming late :pray: 

how regular merges to your repo do you wish ? would it be fine once the video-recordings are out?

**Comment by martin-bertele** [comment]
I'll add the script to generate your readme-view in the coming days and let you know

**Comment by martin-bertele** [comment]
yes we do work together and merge into one :)
https://github.com/bizz84/ftcon24eu_talks/commit/08671ebd33e76b0799ed38aebd82f249710de7d1
